[package]
name = "codernic-ui"
version = "0.1.0"
description = "Codernic Super-App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "codernic_manager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
codernic-lexicon = { workspace = true }
tracing = "0.1"
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-shell = "2"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
tokio = { version = "1", features = ["full"] }
dirs = "5.0"
webbrowser = "1.2.1"
codernic_core_security = { workspace = true }
codernic_core_config = { workspace = true }
configuration_manager = { workspace = true }
tauri-plugin-wdio-webdriver = "1.2.0"
machine-uid = "0.6.0"
md5 = "0.8.1"
git2 = { workspace = true }



[lints]
workspace = true
