apiVersion: v1
kind: Pod
metadata:
  name: ollama-pod
  namespace: deming-showdown
  labels:
    app.kubernetes.io/name: ollama-benchmark
    bench.codernic.dev/engine: ollama
spec:
  restartPolicy: Never
  containers:
  - name: ollama
    image: ollama/ollama:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 11434
    resources:
      limits:
        cpu: "2000m"
        memory: "4Gi"
      requests:
        cpu: "1000m"
        memory: "1Gi"
    volumeMounts:
    - name: models-volume
      mountPath: /root/.ollama
  volumes:
  - name: models-volume
    hostPath:
      path: /home/tadeop/.ollama
      type: DirectoryOrCreate
