apiVersion: v1
kind: Pod
metadata:
  name: llamacpp-pod
  namespace: deming-showdown
  labels:
    app.kubernetes.io/name: llamacpp-benchmark
    bench.codernic.dev/engine: llamacpp
spec:
  restartPolicy: Never
  containers:
  - name: llama-bench
    image: ghcr.io/ggerganov/llama.cpp:full
    imagePullPolicy: IfNotPresent
    command: ["llama-bench", "-m", "/models/Qwen2.5-Coder-1.5B-Instruct-Q4_K_M.gguf", "-n", "128", "-p", "512"]
    resources:
      limits:
        cpu: "2000m"
        memory: "4Gi"
      requests:
        cpu: "1000m"
        memory: "1Gi"
    volumeMounts:
    - name: models-volume
      mountPath: /models
      readOnly: true
  volumes:
  - name: models-volume
    hostPath:
      path: /home/tadeop/codernicapp/models
      type: Directory
