apiVersion: v1
kind: Pod
metadata:
  name: vllm-pod
  namespace: deming-showdown
  labels:
    app.kubernetes.io/name: vllm-benchmark
    bench.codernic.dev/engine: vllm
spec:
  restartPolicy: Never
  containers:
  - name: vllm
    image: vllm/vllm-openai:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8000
    resources:
      limits:
        cpu: "2000m"
        memory: "4Gi"
      requests:
        cpu: "1000m"
        memory: "1Gi"
    volumeMounts:
    - name: models-volume
      mountPath: /models
      readOnly: true
  volumes:
  - name: models-volume
    hostPath:
      path: /home/tadeop/codernicapp/models
      type: Directory
